site_name: DEAP-ER
site_description: Distributed Evolutionary Algorithms in Python - Entirely Reworked
site_url: https://aabmets.github.io/deap-er/
repo_url: https://github.com/aabmets/deap-er
repo_name: aabmets/deap-er
copyright: Copyright 2022 Mattias Aabmets

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - search.highlight

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: true
            show_source: true
            members_order: source
            merge_init_into_class: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets:
      base_path:
        - .
      check_paths: true
  - toc:
      permalink: true

extra_javascript:
  - javascripts/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/contrib/auto-render.min.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.min.css

watch:
  - deap_er

nav:
  - Home: index.md
  - Overview:
      - Introduction: overview/introduction.md
      - Important Differences: overview/differences.md
      - Performance: overview/performance.md
      - Getting Started: overview/getting_started.md
      - Roadmap: overview/roadmap.md
  - Tutorials:
      - Using the Toolbox: tutorials/using_the_toolbox.md
      - Creating Individuals: tutorials/creating_individuals.md
      - Operators and Algorithms: tutorials/operators_and_algorithms.md
      - Columnar Programs: tutorials/columnar_gp.md
      - Logging Statistics: tutorials/logging_statistics.md
      - Multiprocessing: tutorials/multiprocessing.md
      - Using Checkpoints: tutorials/using_checkpoints.md
  - Examples:
      - Genetic Algorithms:
          - One Max: examples/genetic_algorithms/onemax.md
          - Knapsack: examples/genetic_algorithms/knapsack.md
          - N-Queens: examples/genetic_algorithms/nqueens.md
          - Differential Evolution: examples/genetic_algorithms/diff_evo.md
          - Sorting Networks: examples/genetic_algorithms/sorting_net.md
      - Genetic Programming:
          - Even-Parity: examples/genetic_programming/even_parity.md
          - Artificial Ant: examples/genetic_programming/art_ant.md
          - Symbolic Regression: examples/genetic_programming/symb_regr.md
          - Columnar Programs: examples/genetic_programming/columnar_gp.md
      - Evolution Strategies:
          - Standard CMA: examples/evolution_strategies/cma_strat.md
          - CMA restarts: examples/evolution_strategies/cma_restarts.md
          - Multi-Objective CMA: examples/evolution_strategies/mo_cma_strat.md
          - Custom Strategy: examples/evolution_strategies/custom_strat.md
      - Particle Swarms:
          - Single-Swarm: examples/particle_swarm/single_pso.md
          - Multi-Swarm: examples/particle_swarm/multi_pso.md
  - Reference:
      - Base: reference/base.md
      - Creator: reference/creator.md
      - Algorithms: reference/algorithms.md
      - Operators: reference/operators.md
      - Strategies: reference/strategies.md
      - Records: reference/records.md
      - Utilities: reference/utilities.md
      - Benchmarks: reference/benchmarks.md
      - Genetic Programming: reference/gp.md
      - Persistence: reference/persistence.md
      - Type Aliases: reference/aliases.md
  - Bugfixes:
      - DEAP issues: bugfixes/deap_fixes.md
      - Algorithms: bugfixes/algorithms.md
      - Benchmarks: bugfixes/benchmarks.md
      - Creator: bugfixes/creator.md
      - Genetic programming: bugfixes/gp.md
      - Operators: bugfixes/operators.md
      - Persistence: bugfixes/persistence.md
      - Records: bugfixes/records.md
      - Strategies: bugfixes/strategies.md
      - Utilities: bugfixes/utilities.md
